### ISSUE TITLE
Does not work on Centos7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lpechacek/cpuset#19] opened 2015-12-23 07:56 UTC
```
What steps will reproduce the problem?
Running as root:
1. untar cset source
2. python setup.py bdist_rpm  (fix all problems)
3. python setup.py install
4. Verify cset installed w/o problems run "cset" at command line (no args) 
correctly get usage statement.
5. Try to list current shields via:  cset set -l

What is the expected output? What do you see instead?
EXPECTED:
cset:
         Name       CPUs-X    MEMs-X Tasks Subs Path
 ------------ ---------- - ------- - ----- ---- ----------
         root        0-7 y       0 y   141    0 /

ACTUAL:
cset: **> [Errno 2] No such file or directory: '/cpusets//cpus'


What version of the product are you using? On what operating system?
cset: Cpuset (cset) 1.5.6
kernel: Linux 3.10.0-123.el7.x86_64
distro: CentOS Linux release 7.0.1406 (Core)

Please provide any additional information below.
Looks like it installs fine on Centos7 but does not work.



```

Original issue reported on code.google.com by `JonSto...@gmail.com` on 15 Dec 2014 at 6:38

**Comment by lpechacek** [comment] 2015-12-23 13:13
I tend to believe the issue is fixed with commit 22140787836e.  If that's not the case, please reopen this issue.

**Closed by lpechacek** 2015-12-23 13:13 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
